=begin
#NFT Storage API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.1-SNAPSHOT

=end

require 'date'
require 'time'

module NFTStorage
  class PinStatus
    QUEUED = "queued".freeze
    PINNING = "pinning".freeze
    PINNED = "pinned".freeze
    FAILED = "failed".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = PinStatus.constants.select { |c| PinStatus::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #PinStatus" if constantValues.empty?
      value
    end
  end
end
