=begin
#NFT Storage API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.1-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for NFTStorage::ForbiddenErrorResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe NFTStorage::ForbiddenErrorResponse do
  let(:instance) { NFTStorage::ForbiddenErrorResponse.new }

  describe 'test an instance of ForbiddenErrorResponse' do
    it 'should create an instance of ForbiddenErrorResponse' do
      expect(instance).to be_instance_of(NFTStorage::ForbiddenErrorResponse)
    end
  end
  describe 'test attribute "ok"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "error"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
