=begin
#NFT Storage API

## API Reference 

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.1-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for NFTStorage::UnauthorizedErrorResponseError
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe NFTStorage::UnauthorizedErrorResponseError do
  let(:instance) { NFTStorage::UnauthorizedErrorResponseError.new }

  describe 'test an instance of UnauthorizedErrorResponseError' do
    it 'should create an instance of UnauthorizedErrorResponseError' do
      expect(instance).to be_instance_of(NFTStorage::UnauthorizedErrorResponseError)
    end
  end
  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "message"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
