=begin
#NFT Storage API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.1-SNAPSHOT

=end

# Common files
require 'nft_storage/api_client'
require 'nft_storage/api_error'
require 'nft_storage/version'
require 'nft_storage/configuration'

# Models
require 'nft_storage/models/deal'
require 'nft_storage/models/delete_response'
require 'nft_storage/models/error_response'
require 'nft_storage/models/error_response_error'
require 'nft_storage/models/forbidden_error_response'
require 'nft_storage/models/forbidden_error_response_error'
require 'nft_storage/models/get_response'
require 'nft_storage/models/links'
require 'nft_storage/models/links_file'
require 'nft_storage/models/list_response'
require 'nft_storage/models/nft'
require 'nft_storage/models/pin'
require 'nft_storage/models/pin_status'
require 'nft_storage/models/unauthorized_error_response'
require 'nft_storage/models/unauthorized_error_response_error'
require 'nft_storage/models/upload_response'

# APIs
require 'nft_storage/api/nft_storage_api'

module NFTStorage
  class << self
    # Customize default settings for the SDK using block.
    #   NFTStorage.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
