=begin
#NFT Storage API

## API Reference 

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.1-SNAPSHOT

=end

module NFTStorage
  VERSION = '1.0.0'
end
